Оформление блока categories
redly/dl-academy-pavel pull request #4
Opened 2021-02-18 16:16 UTC by pavelkrasulin

Я доделал блок categories с карточками продуктов! Некоторые вопросы написал внутри css.

2021-02-26 09:36 UTC, redly requested changes
Пока писал ревью, ты часть подправил сам
В целом все хорошо, небольшое замечание и нужно двигаться дальше

2021-02-26 09:36 UTC, redly commented on index.html
>                      </li>
По аналогии с тем, как ты исправил `delivery-text` нужно и тут внести изменения
Нет смысла делать разные классы на каждый li, они ничем не отличаются
Как и нет смысла делать разные классы на заголовки

Разные классы стоит задать на div, который у тебя будет отвечать за разные фоны
Но у тебя уже есть ссылка, которую можно использовать как обертку и не добавлять лишний div, так верстка станет более чистой

Итого, если переписать код одного li, может быть что-то такое

```html
<li class="products-list-item"> <!-– абстрактный класс у списка -->
    <a href="#" class="products-list-item-wrapper bg-green"> <!-– добавляем класс для обертки и отдельный класс для фона -->
        <img src="img/apparel.png" alt="Apparel Kids">
        <h3 class="title-h3">Apparel Kids</h3>
    </a>
</li>
```

2021-02-28 15:39 UTC, redly requested changes

2021-02-28 15:39 UTC, redly commented on css/style.css
> +				Нужно ли это переносить из макета?
Нет, не нужно

2021-02-28 15:39 UTC, redly commented on css/style.css
> +			}
В целом этот подход к верстке очень плохой
Тебе приходится подгонять и изображение, и заголовок отдельно

Нужно
1. Сам блок, в котором заголовок и изображение сделать флексом, указать что все что внутри него должно быть по центру вертикально и горизонтально
2. Изображение положить абсолютом, но выравнить его просто по центру
Чтобы располагать блоки, неизвестного размера по центру стоит воспользоваться вот такой практикой
```css
position: absolute;
top: 50%;
left: 50%;
transform: translate(-50%, -50%);
```

То есть ты размещаешь его по центру, а потом через transform сдвигаешь на половину его ширины/высоты, потому что изначально центр будет рассчитываться от верхнего левого угла

Собственно эти два пункта помогут тебе не подгонять каждую категорию, а написать общий код для всех категорий

Твой подход плох тем, что
- При изменении размеров изображений придется менять CSS
- При изменении контента (текста / картинки) опять же придется менять и подгонять CSS

Эти пункты говорят о том, что код будет неподдерживаемым
Как следствие из них вытекает то, что подход этот очень долгий. Для каждой категории приходится писать много своего уникального кода

2021-02-28 15:39 UTC, redly commented on css/style.css
> +		.header-nav-list li a {
Не стоило повышать специфичность селектора
В твоем случае, что `header-nav-list a`, что `header-nav-list li a` делают одно и то же. Нет ссылок вне li, которые ты можешь "задеть" более общим селектором

А вот увеличенная специфичность сильно мешает поддержке кода

Старайся всегда использовать максимум уровень вложенности 2. 
Здесь это возможно, поэтому лучше вернуть как было

2021-02-28 15:39 UTC, redly commented on css/style.css
> +		.product-list li a {
Аналогично комментарию выше

`.product-list li a` -> `.product-list a`

2021-02-28 15:39 UTC, redly commented on css/style.css
> +	height: inherit;
height и так по умолчанию inherit
нет смысла указывать это дополнительно

2021-02-28 15:39 UTC, redly commented on css/style.css
> +		.delivery-list li a {
Аналогично комментариям выше про специфичность

2021-02-28 15:39 UTC, redly commented on css/style.css
> +	height: 61px;
Ограничивая так жестко высоту ты не даешь возможности на переполнение этого блока
Например, если мы добавим больше логотипов верстка поедет

Также она поедет еще и поэтому, что по умолчанию flex-wrap: nowrap

Итого, нужно определиться, что делать. 
Варианта 2: 

1. Если мы хотим ограничить, чтобы логотипы были только в одну строчку и не больше чем в макете, то нужно хотя бы добавить `overflow: hidden`. Тогда при добавлении большего кол-ва логотипов они не будут выходить за границы справа

2. Если мы хотим, чтобы блок нормально себя вел при переполнении (предпочтительный вариант), то нужно
заменить height на min-height и сделать возможным переход на новую строку для логотипов, когда их больше 4х, то есть добавить flex-wrap: wrap

2021-02-28 15:39 UTC, redly commented on css/style.css
> +	.partners-list li:last-child {
Как следствие из пункта 2 выше, партнеров по идее может быть гораздо больше чем 4, поэтому last-child будет работать некорректно. Нам нужно сбрасывать margin-right для каждого 4-го пункта, то есть лучше использовать nth-child(4n)

Но стоит также попробовать сделать просто `justify-content: space-between` для `.partners-list li`. Скорее всего так все будет ок с отступами

2021-02-28 15:39 UTC, redly commented on css/style.css
> +				.footer-col-list li a {
Аналогично комментариям выше про специфичность

2021-02-28 15:39 UTC, redly commented on css/style.css
> +			.footer-col-list li a {
Аналогично комментариям выше про специфичность

2021-02-28 15:39 UTC, redly commented on css/style.css
> +			width: 192px;
Все нормально тут, можно взять с запасом чуть ширину, например, `max-width: 200px`
И лучше заменить на max-width

2021-03-02 16:52 UTC, pavelkrasulin commented on css/style.css
> +			}
Я добавил изображениям position: relative, а заголовкам absolute и они отображаются по центру, нужно ли уточнять разметку через top left и transform, если все работает без этого?

2021-03-02 16:56 UTC, pavelkrasulin commented on css/style.css
> +	.partners-list li:last-child {
До этого пробовал сделать space-between для partners-list, но ничего не работало. Оказалось надо просто указать ширину списка и все заработало без отступов (хотя я думал список наследует ширину контейнера).

2021-03-05 16:17 UTC, redly requested changes

2021-03-05 16:17 UTC, redly commented on css/style.css
> +	height: inherit;
Вот этот комментарий не отработал

2021-03-05 16:17 UTC, redly commented on css/style.css
> +}
Очень плохой подход, селектор звездочку лучше не использовать никогда
Слишком специфичный селектор, потом будет сложно менять эти стили

2021-03-05 16:17 UTC, redly commented on css/style.css
>  }
Аналогично комментарию выше

2021-03-05 16:17 UTC, redly commented on css/style.css
>  }
Ну и это тоже
Лучше задавать какие-то общие классы, так проще будет поддерживать код

2021-03-05 16:17 UTC, redly commented on css/style.css
> +			padding: 11px 180px 11px 60px;
Очень странные padding, обычно display блок должно было хватить, почему такой слева большой получился не ясно. Возможно можно через max-width / text-align: center решить вопрос, это будет лучше

Больше padding плохи тем, что при адаптивном дизайне придется их менять каждый раз, будет много лишнего кода

2021-03-06 19:11 UTC, pavelkrasulin commented on css/style.css
> +			padding: 11px 180px 11px 60px;
Убрал большой padding слева, верстке это не помешало. Если совсем убрать padding и задать max-width то сам блок с цветной подсветкой обрезается, а text-align у меня выравнивает текст ссылки по горизонтали, а мне нужно выравнивать по вертикали. В итоге я не стал пока такой подход оставлять.

2021-03-09 16:00 UTC, redly requested changes

2021-03-09 16:00 UTC, redly commented on catalog.html
> +                <ul class="products-list">
Это должен быть единый список

Просто 4й элемент нужно смещать.
Чтобы такое смещение было только на странице каталога, стоит предусмотреть у списка доп. класс

2021-03-09 16:00 UTC, redly commented on catalog.html
> +        </div>
Лучше было бы обернуть в container оба этих блока, чем дублировать класс
Также это похоже на шапку внутренних страниц

Для main я бы задал класс – `content`
Тогда эту шапку можно было бы разметить как `<div class="content-header container">`

В целом, можно было бы вообще после main сделать общий container для всего, потому что у тебя там весь контент выравнивается, но этот вариант не очень хорошо будет работать для страницы Toys (там фильтры на весь экран)

2021-03-09 16:00 UTC, redly commented on catalog.html
> +                <div class="description-container-wrapper">
Вполне достаточно было бы сделать 2 блока – section полноразмерный и внутри container которым выравнить текст. Зачем три вложенности не ясно. Чем меньше ты используешь элементов в разметке, тем лучше

2021-03-09 16:00 UTC, redly commented on catalog.html
> +        <section class="description">
Название description слишком общее, может использоваться еще много где и стили могут пересечься, будут проблемы

Также блок выглядит как общий текстовый. В такие блоки обычно контент попадает из админки и важно, чтобы все стилизовалось через каскад

Можно задать класс такой `text-content` и остальная стилизация будет `.text-content h2`, `.text-content p`

2021-03-09 16:00 UTC, redly commented on catalog.html
> +                    </p>
Как описал выше стоит избегать доп классов в подобных текстовых блоках

2021-03-09 16:00 UTC, redly commented on css/catalog.css
> +}
Мы неправильно друг друга поняли

Сейчас ты полностью дублируешь стили, которые общие для body, header, footer и тп
Это делать ни в коем случае не стоит

Варианта 2: 
1. Вынести общие стили в common.css. Для каждой новой страницы делать свою таблицу стилей, по типу catalog.css, toys.css
2. Писать все стили в одном файле style.css

Обычно при написании стилей без препроцессора используют второй вариант
Когда есть сборка и более продвинутые инструменты работы используют первый вариант, но там он чуть-чуть трансформируется

Использовать одну таблицу стилей лучше с точки зрения производительности – меньше запросов на сервер, меньше ожидание и как следствие быстрее отрисовка

2021-03-11 12:47 UTC, redly approved these changes
Всё хорошо, за исключением отступов

PR принимаю, а то слишком много изменений уже
Давай дальше опять двигаться мелкими блоками

2021-03-11 12:47 UTC, redly commented on catalog.html
> +                </div>
Поправь тут отступы
Лишние пробелы слева у `<div class="container text-content-container">` и недостаточно пробелов у текста внутри `p`

2021-03-11 12:47 UTC, merged